# Generated by Django 4.2.2 on 2023-06-30 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='ArticleModel',
        ),
    ]
