# Generated by Django 4.2.2 on 2023-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_blogmodel_articlemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(upload_to='article'),
        ),
    ]
